#查询所有的数据库链接
POST http://localhost:8080/reportServer/DBConnection/ListAll HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }
body: {}

###登录请求示例
POST http://localhost:8080/reportServer/user/login HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }

{ UserCode: "system", Pwd: "KfTaJa3vfLE=" }

###查询所有的函数
POST http://localhost:8080/reportServer/function/getAllFunctionName HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }
body: {}

###查询函数用ID
POST http://localhost:8080/reportServer/function/getFunctionByID/36 HTTP/1.1
content-type: application/json
method: POST
credentials: { UserCode: "system", Pwd: "KfTaJa3vfLE=" }

{
    func_id:"37"
}